// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXgUXi6ugcwcn2KPOCgZbJLJpxaD6q0RI',
    appId: '1:569040391479:web:381ecbeaad7b7839ef5eb2',
    messagingSenderId: '569040391479',
    projectId: 'customer-path-quiz-app',
    authDomain: 'customer-path-quiz-app.firebaseapp.com',
    storageBucket: 'customer-path-quiz-app.firebasestorage.app',
    measurementId: 'G-G92PMB7BD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxfp0Cu-JDeEdprLvWAmKOxb8knx0tgMU',
    appId: '1:569040391479:android:5c1e3748b51893d5ef5eb2',
    messagingSenderId: '569040391479',
    projectId: 'customer-path-quiz-app',
    storageBucket: 'customer-path-quiz-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnyH52szSUFoBGak46HeSBcRh0S6RM8CY',
    appId: '1:569040391479:ios:816a3e7c06f5ad80ef5eb2',
    messagingSenderId: '569040391479',
    projectId: 'customer-path-quiz-app',
    storageBucket: 'customer-path-quiz-app.firebasestorage.app',
    iosBundleId: 'com.example.salesQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnyH52szSUFoBGak46HeSBcRh0S6RM8CY',
    appId: '1:569040391479:ios:816a3e7c06f5ad80ef5eb2',
    messagingSenderId: '569040391479',
    projectId: 'customer-path-quiz-app',
    storageBucket: 'customer-path-quiz-app.firebasestorage.app',
    iosBundleId: 'com.example.salesQuizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXgUXi6ugcwcn2KPOCgZbJLJpxaD6q0RI',
    appId: '1:569040391479:web:a2e34376e9c5e38eef5eb2',
    messagingSenderId: '569040391479',
    projectId: 'customer-path-quiz-app',
    authDomain: 'customer-path-quiz-app.firebaseapp.com',
    storageBucket: 'customer-path-quiz-app.firebasestorage.app',
    measurementId: 'G-NJDVJ2YC6D',
  );
}
